In [1]:
import numpy as np

In [2]:
arr= np.array([1,22,321])
arr

array([  1,  22, 321])

In [3]:
arr2= np.array([[1,22,321],[44,555,666]])
arr2

array([[  1,  22, 321],
       [ 44, 555, 666]])

In [6]:
arr3= np.array([[[1,22,321],[44,555,666],[90,33,1232]], [[1,22,321],[44,555,666],[90,33,1232]], [[1,22,321],[44,555,666],[90,33,1232]]])
arr3

array([[[   1,   22,  321],
        [  44,  555,  666],
        [  90,   33, 1232]],

       [[   1,   22,  321],
        [  44,  555,  666],
        [  90,   33, 1232]],

       [[   1,   22,  321],
        [  44,  555,  666],
        [  90,   33, 1232]]])

In [7]:
arr3.ndim

3

In [8]:
arr3[0:2]

array([[[   1,   22,  321],
        [  44,  555,  666],
        [  90,   33, 1232]],

       [[   1,   22,  321],
        [  44,  555,  666],
        [  90,   33, 1232]]])

In [9]:
arr3[0][0,2]

321

In [10]:
arr3[0,1,2]

666

In [11]:
arr3[1,1,1:3]

array([555, 666])

In [2]:
import numpy as np

In [3]:
ar1= np.array([1,2,3])
ar2= np.array([4,5,6])

In [4]:
np.concatenate((ar1,ar2))

array([1, 2, 3, 4, 5, 6])

In [5]:
arr1= np.array([[11,22],[23,34]])
arr2= np.array([[333,21],[29,334]])

In [7]:
ar=np.concatenate((arr1,arr2))

In [8]:
ar.ndim

2

In [9]:
ar.shape

(4, 2)

In [10]:
temperature_data = [25.3, 26.1, 24.8, 23.5, 27.2]
pressure_data = [101.2, 100.8, 101.5, 100.2, 101.0]
humidity_data = [55.2, 54.8, 56.5, 53.7, 55.9]

In [14]:
temperature_data= np.array(temperature_data)
pressure_data= np.array(pressure_data)
humidity_data= np.array(humidity_data)

In [15]:
temp_avg= np.average(temperature_data)
pressure_avg= np.average(pressure_data)
humidity_avg= np.average(humidity_data)

In [17]:
temp_std= np.std(temperature_data)
pressure_std= np.std(pressure_data)
humidity_std= np.std(humidity_data)

In [20]:
temp_max= np.max(temperature_data)
pressure_max= np.max(pressure_data)
humidity_max= np.max(humidity_data)

In [22]:
temp_min= np.min(temperature_data)
pressure_min= np.min(pressure_data)
humidity_min= np.min(humidity_data)